### PR TITLE
Corundum would raise an error about the JSONFormatter missing from .simplecov - but the error didn't explain how to fix it. Worse: corundum-skels generated an incompatible .simplecov file.

### LINKED ISSUE #8: Templating in skels
Specifically, it'd be nice if the name of the project were used.

### PR DESCRIPTION
**Pull request by nyarly**
Both issues now corrected, plus the CLI is a bit slicker - includes setting
the project name explicitly.

[ Fixes #8 #7 #6 ]

### CODE REVIEW

File: lib/corundum/cli/skelfiles.rb [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+      def initialize(args)
+        @args = args
+      end
+      attr_reader :args
+
+      SkelfileScope = Struct.new(:project_name)
+
+      def options
+        @options ||= OptionParser.new do |opti|
+          opti.banner = "Spits on skeleton files to start a gem with.\nUsage: #$0 [options]"
```
Comment (IdahoEv) [inline lib/corundum/cli/skelfiles.rb]: Spits on files?

File: lib/corundum/default_configuration/skel-files/rakefile [hunk 2]
```diff
@@ -15,24 +15,19 @@ module Corundum
...
-      cov.threshold = 70
+    SimpleCov.new(core, rspec) do |cov|
+      cov.threshold = 85
     end
 
     gem = GemBuilding.new(core)
-    cutter = GemCutter.new(core,gem)
-    email = Email.new(core)
-    vc = Git.new(core) do |vc|
+    GemCutter.new(core,gem)
```
Comment (IdahoEv) [inline lib/corundum/default_configuration/skel-files/rakefile]: I'd suggest this template is a good candidate for extensive in-line documentation explaining what each line does, what its defaults are, and what options are available. Especially given that instantiating classes (as opposed to declaring tasks and namespaces) is a generally unfamiliar syntax for a Rakefile.  This is typically the file that most throws me when trying to work on a Corundum gem.

Consider the templated config/routes.rb in Rails and the templated spec_helper.rb by rSpec rails as examples of what I mean.

File: lib/corundum/cli/skelfiles.rb (hunk 1 above)
Comment (nyarly) [inline lib/corundum/cli/skelfiles.rb]: Spits out files, should be
